In [44]:
import torch
print(f"PyTorch Version: {torch.__version__}")
print(f"CUDA Available: {torch.cuda.is_available()}")

# Simple tensor creation
t = torch.tensor([1, 2, 3, 4, 5])
print(f"Tensor: {t}")

PyTorch Version: 2.10.0+cpu
CUDA Available: False
Tensor: tensor([1, 2, 3, 4, 5])


# Tensors in PyTorch

## Definition
A **Tensor** is the fundamental data structure in PyTorch, similar to NumPy arrays but optimized for deep learning. It's an n-dimensional array of numbers that can be computed on both CPU and GPU. Tensors are the core building blocks for neural networks—they represent input data, model parameters (weights), and outputs.

## Key Characteristics

- **Multi-dimensional**: 0-D (scalar), 1-D (vector), 2-D (matrix), 3-D, 4-D, etc.
- **Device support**: Can run on CPU or GPU (CUDA)
- **Automatic differentiation**: Tracks computation for backpropagation (gradient calculation)
- **Optimized for ML**: Designed specifically for neural network operations
- **GPU acceleration**: Much faster than NumPy for large operations

## Tensor Dimensions

- **0-D Tensor (Scalar)**: Single number, shape `()`
- **1-D Tensor (Vector)**: List of numbers, shape `(n,)`
- **2-D Tensor (Matrix)**: Grid of numbers, shape `(m, n)`
- **3-D Tensor**: Cube of numbers, shape `(d, m, n)` - e.g., image (channels, height, width)
- **4-D Tensor**: Batch of images, shape `(batch, channels, height, width)`

## Common Tensor Operations

- **Creation**: `torch.tensor()`, `torch.zeros()`, `torch.ones()`, `torch.randn()`
- **Shape manipulation**: `reshape()`, `view()`, `transpose()`
- **Mathematical**: `+`, `-`, `*`, `/`, `@` (matrix multiplication)
- **Aggregation**: `sum()`, `mean()`, `max()`, `min()`
- **Indexing & slicing**: Same as NumPy arrays

## Note :- 
Tensor & Numpy are sharing memory :- one change will reflect in others

In [45]:
import torch
import numpy as np

print("=" * 60)
print("CREATING TENSORS - Different Methods")
print("=" * 60)

# Method 1: From Python lists/values
print("\n1. Create from lists:")
t1 = torch.tensor([1, 2, 3, 4, 5])
print(f"1-D tensor: {t1}")
print(f"Shape: {t1.shape}, Data type: {t1.dtype}")

t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"\n2-D tensor:\n{t2}")
print(f"Shape: {t2.shape}")

# Method 2: Special initializations
print("\n2. Special initializations:")
zeros = torch.zeros(3, 4)  # 3x4 matrix of zeros
print(f"Zeros (3x4):\n{zeros}")

ones = torch.ones(2, 3)  # 2x3 matrix of ones
print(f"\nOnes (2x3):\n{ones}")



CREATING TENSORS - Different Methods

1. Create from lists:
1-D tensor: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5]), Data type: torch.int64

2-D tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

2. Special initializations:
Zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [46]:
import torch
# Method 3: Random values
print("\n3. Random tensors:")
rand = torch.rand(2, 3)  # Uniform distribution [0, 1)
print(f"Random uniform (2x3):\n{rand}")

randn = torch.randn(2, 3)  # Normal distribution
print(f"\nRandom normal (2x3):\n{randn}")

# Method 4: From NumPy arrays
print("\n4. From NumPy arrays:")
np_array = np.array([1, 2, 3, 4, 5])
tensor_from_np = torch.from_numpy(np_array)
print(f"From NumPy: {tensor_from_np}")
print(f"Type: {tensor_from_np.dtype}")


3. Random tensors:
Random uniform (2x3):
tensor([[0.6914, 0.4826, 0.3020],
        [0.0639, 0.4470, 0.0319]])

Random normal (2x3):
tensor([[-1.3320, -1.4458, -1.8741],
        [ 0.2774, -0.4473,  0.5811]])

4. From NumPy arrays:
From NumPy: tensor([1, 2, 3, 4, 5])
Type: torch.int64


In [47]:
import torch

print("=" * 60)
print("TENSOR PROPERTIES AND ATTRIBUTES")
print("=" * 60)

# Create a sample tensor
tensor = torch.tensor([[1.0, 2.0, 3.0], 
                       [4.0, 5.0, 6.0]])

print("\nTensor:")
print(tensor)

print(f"\nShape: {tensor.shape}")
print(f"Size: {tensor.size()}")
print(f"Dimensions (ndim): {tensor.ndim}")
print(f"Total elements: {tensor.numel()}")
print(f"Data type: {tensor.dtype}")
print(f"Device: {tensor.device}")

# Changing data type
print("\n--- Type conversion ---")
tensor_int = tensor.int()
print(f"As int: {tensor_int}, dtype: {tensor_int.dtype}")

tensor_bool = tensor > 3
print(f"As bool (values > 3): {tensor_bool}, dtype: {tensor_bool.dtype}")

# Reshape tensor
print("\n--- Reshaping ---")
original = torch.arange(12)  # [0, 1, 2, ..., 11]
print(f"Original (1-D): {original}")

reshaped = original.reshape(3, 4)
print(f"Reshaped (3x4):\n{reshaped}")

viewed = original.view(2, 6)
print(f"View (2x6):\n{viewed}")

# Flattening
print(f"Flattened: {reshaped.flatten()}")

TENSOR PROPERTIES AND ATTRIBUTES

Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Shape: torch.Size([2, 3])
Size: torch.Size([2, 3])
Dimensions (ndim): 2
Total elements: 6
Data type: torch.float32
Device: cpu

--- Type conversion ---
As int: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32), dtype: torch.int32
As bool (values > 3): tensor([[False, False, False],
        [ True,  True,  True]]), dtype: torch.bool

--- Reshaping ---
Original (1-D): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped (3x4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
View (2x6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [48]:
import torch

print("=" * 60)
print("TENSOR OPERATIONS")
print("=" * 60)

# Create sample tensors
t1 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
t2 = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

print("t1:")
print(t1)
print("\nt2:")
print(t2)

# Arithmetic operations
print("\n--- Arithmetic Operations ---")
print(f"t1 + t2 =\n{t1 + t2}")
print(f"\nt1 - t2 =\n{t1 - t2}")
print(f"\nt1 * t2 (element-wise) =\n{t1 * t2}")
print(f"\nt1 / t2 (element-wise) =\n{t1 / t2}")

# Matrix multiplication
print("\n--- Matrix Multiplication ---")
print(f"t1 @ t2 (matrix mult) =\n{t1 @ t2}")
print(f"\nt2.T (transpose) =\n{t2.T}")

# Indexing and slicing
print("\n--- Indexing and Slicing ---")
print(f"t1[0] (first row): {t1[0]}")
print(f"t1[:, 1] (second column): {t1[:, 1]}")
print(f"t1[1, 0] (element at [1,0]): {t1[1, 0]}")

# Aggregation operations
print("\n--- Aggregation Operations ---")
print(f"t1.sum(): {t1.sum()}")
print(f"t1.mean(): {t1.mean()}")
print(f"t1.max(): {t1.max()}")
print(f"t1.min(): {t1.min()}")
print(f"t1.sum(dim=0) (sum per column): {t1.sum(dim=0)}")
print(f"t1.sum(dim=1) (sum per row): {t1.sum(dim=1)}")

TENSOR OPERATIONS
t1:
tensor([[1., 2.],
        [3., 4.]])

t2:
tensor([[5., 6.],
        [7., 8.]])

--- Arithmetic Operations ---
t1 + t2 =
tensor([[ 6.,  8.],
        [10., 12.]])

t1 - t2 =
tensor([[-4., -4.],
        [-4., -4.]])

t1 * t2 (element-wise) =
tensor([[ 5., 12.],
        [21., 32.]])

t1 / t2 (element-wise) =
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

--- Matrix Multiplication ---
t1 @ t2 (matrix mult) =
tensor([[19., 22.],
        [43., 50.]])

t2.T (transpose) =
tensor([[5., 7.],
        [6., 8.]])

--- Indexing and Slicing ---
t1[0] (first row): tensor([1., 2.])
t1[:, 1] (second column): tensor([2., 4.])
t1[1, 0] (element at [1,0]): 3.0

--- Aggregation Operations ---
t1.sum(): 10.0
t1.mean(): 2.5
t1.max(): 4.0
t1.min(): 1.0
t1.sum(dim=0) (sum per column): tensor([4., 6.])
t1.sum(dim=1) (sum per row): tensor([3., 7.])


In [49]:
import torch

print("=" * 60)
print("AUTOMATIC DIFFERENTIATION (Gradients)")
print("=" * 60)

# Create tensor with requires_grad=True to track gradients
print("\nScenario: Simple loss calculation")
x = torch.tensor([2.0, 3.0], requires_grad=True)
w = torch.tensor([1.0, 2.0], requires_grad=True)

print(f"x: {x}")
print(f"w: {w}")

# Forward pass (computation)
y = (x * w).sum()  # y = 2*1 + 3*2 = 8
print(f"\ny = (x * w).sum() = {y}")
print(f"y requires_grad: {y.requires_grad}")

# Backward pass (compute gradients)
y.backward()  # Compute dy/dx and dy/dw

print(f"\nAfter backward():")
print(f"x.grad (dy/dx): {x.grad}")  # [1.0, 2.0] (same as w)
print(f"w.grad (dy/dw): {w.grad}")  # [2.0, 3.0] (same as x)

print("\nThis is how neural networks learn!")
print("The gradients tell us how much each parameter affected the output.")
print("\n--- Practical Example: Simple Neural Network Step ---")

# Reset gradients for new example
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
W = torch.tensor([[0.1, 0.2], [0.3, 0.4]], requires_grad=True)

# Forward pass
output = x @ W
loss = output.sum()

print(f"Input x:\n{x}")
print(f"\nWeight matrix W:\n{W}")
print(f"\nOutput:\n{output}")
print(f"\nLoss: {loss}")

# Backward pass
loss.backward()

print(f"\nGradients computed!")
print(f"x.grad:\n{x.grad}")
print(f"\nW.grad:\n{W.grad}")

print("\nThese gradients are used by the optimizer to update W and improve the model!")

AUTOMATIC DIFFERENTIATION (Gradients)

Scenario: Simple loss calculation
x: tensor([2., 3.], requires_grad=True)
w: tensor([1., 2.], requires_grad=True)

y = (x * w).sum() = 8.0
y requires_grad: True

After backward():
x.grad (dy/dx): tensor([1., 2.])
w.grad (dy/dw): tensor([2., 3.])

This is how neural networks learn!
The gradients tell us how much each parameter affected the output.

--- Practical Example: Simple Neural Network Step ---
Input x:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

Weight matrix W:
tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]], requires_grad=True)

Output:
tensor([[0.7000, 1.0000],
        [1.5000, 2.2000]], grad_fn=<MmBackward0>)

Loss: 5.400000095367432

Gradients computed!
x.grad:
tensor([[0.3000, 0.7000],
        [0.3000, 0.7000]])

W.grad:
tensor([[4., 4.],
        [6., 6.]])

These gradients are used by the optimizer to update W and improve the model!


In [50]:
import torch
import numpy as np

print("=" * 60)
print("TENSORS vs NumPy Arrays")
print("=" * 60)

# Create equivalent data in NumPy and PyTorch
np_array = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.tensor([1, 2, 3, 4, 5])

print("\nNumPy array:")
print(f"Type: {type(np_array)}")
print(f"Data: {np_array}")
print(f"dtype: {np_array.dtype}")

print("\nPyTorch tensor:")
print(f"Type: {type(torch_tensor)}")
print(f"Data: {torch_tensor}")
print(f"dtype: {torch_tensor.dtype}")

# Device management
print("\n" + "=" * 60)
print("DEVICE MANAGEMENT")
print("=" * 60)

print(f"\nCUDA available: {torch.cuda.is_available()}")
print(f"CUDA device count: {torch.cuda.device_count()}")

# Create tensor on CPU
t_cpu = torch.tensor([1.0, 2.0, 3.0])
print(f"\nTensor on CPU: {t_cpu.device}")

# If CUDA available, move to GPU (commented since we're on CPU)
# t_gpu = t_cpu.cuda()
# print(f"Tensor on GPU: {t_gpu.device}")

print("\n--- Key Differences: Tensors vs NumPy ---")
print("NumPy:")
print("  + Good for general numerical computing")
print("  + CPU only")
print("  - No automatic differentiation")
print("  - No GPU support")

print("\nPyTorch Tensors:")
print("  + GPU acceleration possible")
print("  + Automatic differentiation (backward pass)")
print("  + Optimized for deep learning")
print("  + Can track computation graph")
print("  - Primarily for ML/neural networks")

print("\n" + "=" * 60)
print("CONVERSION BETWEEN NumPy AND PyTorch")
print("=" * 60)

# NumPy to PyTorch
np_arr = np.array([[1, 2], [3, 4]])
torch_from_np = torch.from_numpy(np_arr)
print(f"\nNumPy array:\n{np_arr}")
print(f"To PyTorch tensor:\n{torch_from_np}")

# PyTorch to NumPy
torch_t = torch.tensor([[5, 6], [7, 8]])
np_from_torch = torch_t.numpy()
print(f"\nPyTorch tensor:\n{torch_t}")
print(f"To NumPy array:\n{np_from_torch}")

TENSORS vs NumPy Arrays

NumPy array:
Type: <class 'numpy.ndarray'>
Data: [1 2 3 4 5]
dtype: int64

PyTorch tensor:
Type: <class 'torch.Tensor'>
Data: tensor([1, 2, 3, 4, 5])
dtype: torch.int64

DEVICE MANAGEMENT

CUDA available: False
CUDA device count: 0

Tensor on CPU: cpu

--- Key Differences: Tensors vs NumPy ---
NumPy:
  + Good for general numerical computing
  + CPU only
  - No automatic differentiation
  - No GPU support

PyTorch Tensors:
  + GPU acceleration possible
  + Automatic differentiation (backward pass)
  + Optimized for deep learning
  + Can track computation graph
  - Primarily for ML/neural networks

CONVERSION BETWEEN NumPy AND PyTorch

NumPy array:
[[1 2]
 [3 4]]
To PyTorch tensor:
tensor([[1, 2],
        [3, 4]])

PyTorch tensor:
tensor([[5, 6],
        [7, 8]])
To NumPy array:
[[5 6]
 [7 8]]
