# Arange Function

Definition: 
numpy.arange(start, stop, step, dtype=None) : returns a 1‑D ndarray of evenly spaced values in the half-open interval [start, stop) with spacing step. start defaults to 0 if omitted; stop is required. For integer steps the values are exact; for non-integer step use caution due to floating-point rounding — consider numpy.linspace for fixed-count sequences.

Parameters:

- start: starting value (optional; default 0)
- stop: end value (exclusive)
- step: spacing between values (optional; default 1)
- dtype: desired output type (optional)
- Return: ndarray of values: start, start+step, start+2*step, ..., < stop.

Examples:

* np.arange(5) → array([0, 1, 2, 3, 4])
* np.arange(2, 7) → array([2, 3, 4, 5, 6])
* np.arange(0, 1, 0.2) → array([0. , 0.2, 0.4, 0.6, 0.8]) (watch floating error)
* np.arange(0, 1+1e-9, 0.2) or np.linspace(0,1,6) if you need inclusive endpoint

In [31]:
import numpy as np

# numpy arange examples
a = np.arange(10)            # 0..9
b = np.arange(1, 10, 2)      # 1,3,5,7,9
c = np.arange(0, 1, 0.2)     # 0. ,0.2,0.4,0.6,0.8

print("a:", a)
print("b:", b)
print("c:", c)

# reshape example
a2 = a.reshape(5, 2) # reshape a to 5 rows and 2 columns
print("a reshaped:\n", a2)

# reshape example
a2 = a.reshape(2, -1) # reshape a to 2 rows and automatically determine the number of columns
print("a reshaped:\n", a2)

# simple computation with arange
print("squares of a:", a**2)

a: [0 1 2 3 4 5 6 7 8 9]
b: [1 3 5 7 9]
c: [0.  0.2 0.4 0.6 0.8]
a reshaped:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
a reshaped:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
squares of a: [ 0  1  4  9 16 25 36 49 64 81]


# Linspace

Definition: 
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) — returns num evenly spaced samples over the interval [start, stop] (inclusive when endpoint=True). Use linspace when you need a fixed number of points; it's more reliable for floating-point endpoints than arange.

Parameters:

* start: first value
* stop: last value (included if endpoint=True)
* num: number of samples (default 50)
* endpoint: include stop (default True)
* retstep: if True, return (samples, step)
* dtype: output data type
* Return: ndarray of shape (num,) (or (samples, step) if retstep=True).

Examples:

* np.linspace(0, 1, 5) → array([0. , 0.25, 0.5 , 0.75, 1. ])
* np.linspace(0, 1, 6, endpoint=False) → array([0. , 0.16666667, 0.33333333, 0.5 , 0.66666667, 0.83333333])
* np.linspace(0, 1, 6, retstep=True) → (array([0. , 0.2, 0.4, 0.6, 0.8, 1. ]), 0.2)

In [32]:
import numpy as np

# numpy linspace examples
x = np.linspace(0, 1, 5)                 # 5 samples including endpoint
y, step = np.linspace(0, 1, 6, retstep=True)  # return samples and step
z = np.linspace(0, 1, 6, endpoint=False)  # exclude endpoint

print('x ->', x)
print('y ->', y)
print('step ->', step)
print('z ->', z)

x -> [0.   0.25 0.5  0.75 1.  ]
y -> [0.  0.2 0.4 0.6 0.8 1. ]
step -> 0.2
z -> [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333]


# ReShape


Definition: numpy.reshape(a, newshape, order='C') — returns an array view with shape `newshape` without changing data order when possible. `-1` can be used to infer one dimension.

Parameters:

* a: array to reshape
* newshape: int or tuple of ints; may contain one `-1` to infer size
* order: {'C','F','A'} (row-major, column-major, or Fortran/Array order)

Return: reshaped `ndarray` view when possible; otherwise a copy.

In [33]:
import numpy as np

# create 1-D array and reshape examples
a = np.arange(12)           # 0..11
print('a ->', a)

b = a.reshape(3, 4)         # 3 rows, 4 cols
print('\nb (3,4):\n', b)

c = a.reshape(4, -1)        # -1 infers the missing dimension
print('\nc (4,-1):\n', c)

# reshape may return a view (no copy) when possible
b[0,0] = 999
print('\na after modifying b:', a)

# use order to reshape in Fortran-style if needed
d = np.reshape(a, (6,2), order='F') # 
print('\nd Fortran-order (6,2):\n', d)

a -> [ 0  1  2  3  4  5  6  7  8  9 10 11]

b (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

c (4,-1):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

a after modifying b: [999   1   2   3   4   5   6   7   8   9  10  11]

d Fortran-order (6,2):
 [[999   6]
 [  1   7]
 [  2   8]
 [  3   9]
 [  4  10]
 [  5  11]]


# Slicing

Definition: Slicing in NumPy uses the `start:stop:step` notation to extract subarrays. It works for 1-D and multi-dimensional arrays (use commas to separate axes, e.g., `arr[row_start:row_stop, col_start:col_stop]`). Negative indices count from the end. Slicing returns a view when possible, so changes to the slice may modify the original array.

Key points:

* `start` is inclusive, `stop` is exclusive
* `step` defaults to 1; use negative `step` to reverse
* Use `:` to select entire axis, and `-1` for last element
* Slicing often returns a view (not a copy)

In [37]:
import numpy as np

# 1-D slicing
a = np.arange(30)           # 0..29
print('a ->', a)
print('a[2:7] ->', a[2:7])      # indices 2..6
print('a[:5] ->', a[:5])        # first five
print('a[::2] ->', a[::2])      # every other element
print('a[::-1] ->', a[::-1])    # reversed
print('a[-3:] ->', a[-3:])      # last three

# 2-D slicing
b = a.reshape(6, 5)
print('\nb (6,5):\n', b)
print('b[0,2] ->', b[0,2])       # single element
print('b[0,:] ->', b[0,:])       # first row
print('b[:,1] ->', b[:,1])       # second column
print('b[2:5,1:4] ->\n', b[2:5,1:4])  # submatrix

# modifying a slice (view) affects the original array
sub = b[:, :2]
sub[:] = -1
print('\nb after modifying slice:', b)
print('original a now:', a)

a -> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
a[2:7] -> [2 3 4 5 6]
a[:5] -> [0 1 2 3 4]
a[::2] -> [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
a[::-1] -> [29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]
a[-3:] -> [27 28 29]

b (6,5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
b[0,2] -> 2
b[0,:] -> [0 1 2 3 4]
b[:,1] -> [ 1  6 11 16 21 26]
b[2:5,1:4] ->
 [[11 12 13]
 [16 17 18]
 [21 22 23]]

b after modifying slice: [[-1 -1  2  3  4]
 [-1 -1  7  8  9]
 [-1 -1 12 13 14]
 [-1 -1 17 18 19]
 [-1 -1 22 23 24]
 [-1 -1 27 28 29]]
original a now: [-1 -1  2  3  4 -1 -1  7  8  9 -1 -1 12 13 14 -1 -1 17 18 19 -1 -1 22 23
 24 -1 -1 27 28 29]
