# Masking (Boolean Indexing)

Definition: Masking (boolean indexing) in NumPy uses a boolean array of the same shape as the target array to select elements. The mask has `True` for elements to keep and `False` for elements to discard. Masking returns a 1-D view or copy of the selected elements and is commonly used for filtering, conditional selection, and assignment.

Key points:

- Create masks using comparisons (e.g., `arr > 0`) or logical operations (`&`, `|`, `~`)
- Use `arr[mask]` to select elements where mask is True
- Assign with masks: `arr[mask] = value` updates original array (in-place)
- Combine masks with `np.logical_and`, `np.logical_or` for clarity when needed
- Masking returns a 1-D array of selected elements; to keep shape use `np.where` or reshape back

In [3]:
import numpy as np

# create an example array
a = np.array([ -3, -1, 0, 2, 5, 8 ])
print('a ->', a)

# simple mask: select positive values
mask = a > 0
print('mask ->', mask)
print('a[mask] ->', a[mask])

# assign using mask (in-place modification)
a[mask] = a[mask] * 10
print('a after a[mask] *= 10 ->', a)

# combined mask: values between 0 and 6 (inclusive of lower bound)
mask2 = (a >= 0) & (a <= 6)
print('mask2 ->', mask2)
print('a[mask2] ->', a[mask2])

# use np.where to get indices satisfying condition
indices = np.where(a < 0)
print('indices where a < 0 ->', indices)
print('a[indices] ->', a[indices])

# boolean mask on 2-D arrays
b = np.arange(12).reshape(3,4) - 6  # values from -6 to 5
print('\nb (3,4):\n', b)
mask3 = b < 0
print('mask3:\n', mask3)
print('b[mask3] ->', b[mask3])

# set all negative values to 0 using masking
b[mask3] = 0
print('b after setting negatives to 0:\n', b)

a -> [-3 -1  0  2  5  8]
mask -> [False False False  True  True  True]
a[mask] -> [2 5 8]
a after a[mask] *= 10 -> [-3 -1  0 20 50 80]
mask2 -> [False False  True False False False]
a[mask2] -> [0]
indices where a < 0 -> (array([0, 1]),)
a[indices] -> [-3 -1]

b (3,4):
 [[-6 -5 -4 -3]
 [-2 -1  0  1]
 [ 2  3  4  5]]
mask3:
 [[ True  True  True  True]
 [ True  True False False]
 [False False False False]]
b[mask3] -> [-6 -5 -4 -3 -2 -1]
b after setting negatives to 0:
 [[0 0 0 0]
 [0 0 0 1]
 [2 3 4 5]]


# Vectorization

Definition: Vectorization in NumPy is applying operations element-wise to entire arrays without explicit loops. Instead of iterating with Python `for` loops, use NumPy's broadcasting and universal functions (`ufuncs`) to operate on arrays directly. This is much faster because NumPy operations run in compiled C code. For custom functions, use `np.vectorize()` to convert a scalar function to one that operates on arrays.

Key points:

- Built-in NumPy functions (e.g., `np.sqrt`, `np.sin`, `np.exp`) are already vectorized
- **Broadcasting**: operations on arrays of different shapes align and apply element-wise when compatible
- **`np.vectorize(func)`**: converts a scalar function to an array function; slower than native ufuncs but convenient
- Avoid explicit Python loops when NumPy offers native operations—vectorized code is 10-100x faster
- Use `np.where(condition, iftrue, iffalse)` for conditional vectorization instead of loops

In [4]:
import numpy as np

# Vectorization with built-in math functions
a = np.array([0, 1, 4, 9, 16])
print('a ->', a)
print('np.sqrt(a) ->', np.sqrt(a))    # square root, element-wise
print('np.square(a) ->', np.square(a))  # square, element-wise

# trigonometric functions
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print('\nangles ->', angles)
print('np.sin(angles) ->', np.sin(angles))
print('np.cos(angles) ->', np.cos(angles))

# exponential and log
x = np.array([1, 2, 3, 4, 5])
print('\nx ->', x)
print('np.exp(x) ->', np.exp(x))     # e^x
print('np.log(x) ->', np.log(x))     # natural log

# Broadcasting: different shapes work automatically
print('\n--- Broadcasting Example ---')
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([10, 20, 30])
print('b:\n', b)
print('c:', c)
print('b + c (broadcasts c to each row):\n', b + c)
print('b * c:\n', b * c)

a -> [ 0  1  4  9 16]
np.sqrt(a) -> [0. 1. 2. 3. 4.]
np.square(a) -> [  0   1  16  81 256]

angles -> [0.         0.52359878 0.78539816 1.04719755 1.57079633]
np.sin(angles) -> [0.         0.5        0.70710678 0.8660254  1.        ]
np.cos(angles) -> [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

x -> [1 2 3 4 5]
np.exp(x) -> [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
np.log(x) -> [0.         0.69314718 1.09861229 1.38629436 1.60943791]

--- Broadcasting Example ---
b:
 [[1 2 3]
 [4 5 6]]
c: [10 20 30]
b + c (broadcasts c to each row):
 [[11 22 33]
 [14 25 36]]
b * c:
 [[ 10  40  90]
 [ 40 100 180]]


In [5]:
import numpy as np

# Vectorization with custom functions using np.vectorize
def custom_func(x):
    """Custom function: return x^2 if x >= 0, else return 0"""
    if x >= 0:
        return x ** 2
    else:
        return 0

# Without vectorization: slow loop
a = np.array([-2, -1, 0, 1, 2, 3])
print('a ->', a)
result_loop = [custom_func(x) for x in a]
print('result via loop ->', result_loop)

# With vectorization: faster
vec_custom_func = np.vectorize(custom_func)
result_vec = vec_custom_func(a)
print('result via np.vectorize ->', result_vec)

# Another example: convert temperature from Celsius to Fahrenheit
def celsius_to_fahrenheit(c):
    return (c * 9/5) + 32

temps_c = np.array([-40, 0, 20, 37, 100])
print('\ntemperatures (C) ->', temps_c)

vec_convert = np.vectorize(celsius_to_fahrenheit)
temps_f = vec_convert(temps_c)
print('temperatures (F) ->', temps_f)

# Alternative: use vectorized operations directly (faster)
temps_f_direct = (temps_c * 9/5) + 32
print('temperatures (F) via direct ops ->', temps_f_direct)

# Use np.where for conditional vectorization (faster than np.vectorize)
print('\n--- Using np.where for efficiency ---')
result_where = np.where(a >= 0, a**2, 0)
print('np.where result ->', result_where)

a -> [-2 -1  0  1  2  3]
result via loop -> [0, 0, np.int64(0), np.int64(1), np.int64(4), np.int64(9)]
result via np.vectorize -> [0 0 0 1 4 9]

temperatures (C) -> [-40   0  20  37 100]
temperatures (F) -> [-40.   32.   68.   98.6 212. ]
temperatures (F) via direct ops -> [-40.   32.   68.   98.6 212. ]

--- Using np.where for efficiency ---
np.where result -> [0 0 0 1 4 9]


In [7]:
def custom_func_vec(x, b):
    "return a-b if a>b else return a+b"
    return np.where(x > b, x - b, x + b)
# Example usage
x = np.array([1, 2, 3, 4, 5])
b = 3
result = custom_func_vec(x, b)
print('custom_func_vec result ->', result)

custom_func_vec result -> [4 5 6 1 2]
