# Stacking Functions

Definition: Stacking functions in NumPy combine multiple arrays into a single array along a specified axis. Common functions are `np.vstack()` (stack vertically/rows), `np.hstack()` (stack horizontally/columns), `np.dstack()` (stack along depth/3rd dimension), `np.stack()` (stack along a new axis with full control), and `np.concatenate()` (join arrays along an existing axis).

Key points:

- **`np.vstack()`**: stack arrays row-wise (equivalent to concatenate along axis 0 for 2-D)
- **`np.hstack()`**: stack arrays column-wise (equivalent to concatenate along axis 1 for 2-D)
- **`np.stack()`**: create a new axis and stack arrays there; all input arrays must have same shape
- **`np.dstack()`**: stack arrays along third dimension (depth)
- **`np.concatenate()`**: join arrays along an existing axis; more general and flexible
- **`np.column_stack()`**: stack 1-D arrays as columns (for 1-D arrays, similar to hstack)

In [31]:
import numpy as np

a = np.arange(4).reshape(2, 2)
b = np.arange(4, 8).reshape(2, 2)    
print('a:\n', a)
print('\nb:\n', b)

# vstack: stack vertically (along axis 0 / rows)
v = np.vstack((a, b))
print('\nnp.vstack((a, b)):\n', v)

# hstack: stack horizontally (along axis 1 / columns)
h = np.hstack((a, b))
print('\nnp.hstack((a, b)):\n', h)

# concatenate along axis 0 (equivalent to vstack)
c0 = np.concatenate((a, b), axis=0)
print('\nnp.concatenate((a, b), axis=0):\n', c0)

# concatenate along axis 1 (equivalent to hstack)
c1 = np.concatenate((a, b), axis=1)
print('\nnp.concatenate((a, b), axis=1):\n', c1)

a:
 [[0 1]
 [2 3]]

b:
 [[4 5]
 [6 7]]

np.vstack((a, b)):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

np.hstack((a, b)):
 [[0 1 4 5]
 [2 3 6 7]]

np.concatenate((a, b), axis=0):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

np.concatenate((a, b), axis=1):
 [[0 1 4 5]
 [2 3 6 7]]


In [32]:
import numpy as np

# stack: create a new axis
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# stack along axis 0 (creates shape (2, 2, 2))
s0 = np.stack((a, b), axis=0)
print('np.stack((a, b), axis=0) shape:', s0.shape)
print(s0)

# stack along axis 2 (depth dimension)
s2 = np.stack((a, b), axis=2)
print('\nnp.stack((a, b), axis=2) shape:', s2.shape)
print(s2)

# dstack: stack along depth (third dimension)
d = np.dstack((a, b))
print('\nnp.dstack((a, b)) shape:', d.shape)
print(d)

np.stack((a, b), axis=0) shape: (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.stack((a, b), axis=2) shape: (2, 2, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

np.dstack((a, b)) shape: (2, 2, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [33]:
import numpy as np

# Stacking 1-D arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

print('x:', x)
print('y:', y)
print('z:', z)

# vstack on 1-D arrays: treats them as rows
v = np.vstack((x, y, z))
print('\nnp.vstack((x, y, z)):\n', v)

# hstack on 1-D arrays: concatenates into 1-D
h = np.hstack((x, y, z))
print('\nnp.hstack((x, y, z)):', h)

# column_stack: treat 1-D arrays as columns
col = np.column_stack((x, y, z))
print('\nnp.column_stack((x, y, z)):\n', col)

# dstack on 1-D arrays
d = np.dstack((x, y, z))
print('\nnp.dstack((x, y, z)) shape:', d.shape)
print(d)

a = np.vstack((x, y))
print('a:\n', a)
                     
# Transpose y to make it a column vector and then stack
b = np.vstack((x, y.T))
print('b:\n', b)


x: [1 2 3]
y: [4 5 6]
z: [7 8 9]

np.vstack((x, y, z)):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

np.hstack((x, y, z)): [1 2 3 4 5 6 7 8 9]

np.column_stack((x, y, z)):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

np.dstack((x, y, z)) shape: (1, 3, 3)
[[[1 4 7]
  [2 5 8]
  [3 6 9]]]
a:
 [[1 2 3]
 [4 5 6]]
b:
 [[1 2 3]
 [4 5 6]]


In [34]:
import numpy as np

a = np.arange(4).reshape(2, 2)
b = np.arange(4, 8).reshape(2, 2)    
print('a:\n', a)
print('\nb:\n', b)


hstack = np.hstack((a, b))
print('\nnp.hstack((a, b)):\n', hstack) 

hstackT = np.hstack((a, b.T))
print('\nnp.hstack((a, b.T)):\n', hstackT)

vstack = np.vstack((a, b))
print('\nnp.vstack((a, b)):\n', vstack)

vstackT = np.vstack((a.T, b.T))
print('\nnp.vstack((a, b.T)):\n', vstackT)





a:
 [[0 1]
 [2 3]]

b:
 [[4 5]
 [6 7]]

np.hstack((a, b)):
 [[0 1 4 5]
 [2 3 6 7]]

np.hstack((a, b.T)):
 [[0 1 4 6]
 [2 3 5 7]]

np.vstack((a, b)):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

np.vstack((a, b.T)):
 [[0 2]
 [1 3]
 [4 6]
 [5 7]]


# Special Matrix Functions

Definition: NumPy provides functions to create special matrices and arrays with specific properties. Common functions include `np.zeros()` (all zeros), `np.ones()` (all ones), `np.eye()` (identity matrix), `np.diag()` (diagonal matrix), `np.full()` (filled with constant value), and `np.identity()` (identity matrix).

Key points:

- **`np.zeros(shape)`**: create array filled with zeros
- **`np.ones(shape)`**: create array filled with ones
- **`np.eye(n, m=None)`**: create n×m identity matrix (1s on diagonal, 0s elsewhere)
- **`np.identity(n)`**: create n×n identity matrix
- **`np.diag(v, k=0)`**: create diagonal matrix from vector `v`, or extract diagonal from matrix; `k` controls offset
- **`np.full(shape, fill_value)`**: create array filled with specified constant value
- **`np.tile(a, reps)`**: repeat array `a` according to `reps`
- **`np.repeat(a, repeats, axis)`**: repeat array elements along axis

In [35]:
import numpy as np

# Create special matrices
print('--- Creating Special Matrices ---\n')

# zeros and ones
zeros = np.zeros((2, 3))
print('np.zeros((2, 3)):\n', zeros)

ones = np.ones((3, 2))
print('\nnp.ones((3, 2)):\n', ones)

# eye: identity matrix
eye = np.eye(3)
print('\nnp.eye(3):\n', eye)

# diagonal matrix from vector
v = np.array([1, 2, 3, 4])
diag = np.diag(v)
print('\nnp.diag([1, 2, 3, 4]):\n', diag)

# extract diagonal from matrix
mat = np.arange(1, 10).reshape(3, 3)
print('\nmat:\n', mat)
diag_extracted = np.diag(mat)
print('np.diag(mat):', diag_extracted)

# full: fill with constant value
full = np.full((2, 4), 7)
print('\nnp.full((2, 4), 7):\n', full)

--- Creating Special Matrices ---

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]

np.ones((3, 2)):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.diag([1, 2, 3, 4]):
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

mat:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
np.diag(mat): [1 5 9]

np.full((2, 4), 7):
 [[7 7 7 7]
 [7 7 7 7]]


In [36]:
import numpy as np

# tile and repeat
print('--- Tile and Repeat ---\n')

a = np.array([[1, 2], [3, 4]])
print('a:\n', a)

# tile: repeat entire array
tiled = np.tile(a, (2, 3))
print('\nnp.tile(a, (2, 3)):\n', tiled)

# repeat: repeat elements
b = np.array([1, 2, 3])
repeated = np.repeat(b, 3)
print('\nnp.repeat([1, 2, 3], 3):', repeated)

# repeat along axis for 2-D
repeated_axis = np.repeat(a, 2, axis=0)
print('\nnp.repeat(a, 2, axis=0):\n', repeated_axis)

repeated_axis1 = np.repeat(a, 2, axis=1)
print('\nnp.repeat(a, 2, axis=1):\n', repeated_axis1)

--- Tile and Repeat ---

a:
 [[1 2]
 [3 4]]

np.tile(a, (2, 3)):
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]

np.repeat([1, 2, 3], 3): [1 1 1 2 2 2 3 3 3]

np.repeat(a, 2, axis=0):
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]

np.repeat(a, 2, axis=1):
 [[1 1 2 2]
 [3 3 4 4]]


In [40]:
import numpy as np

# diagonal with offset
print('--- Diagonal Matrices with Offset ---\n')

# diagonal on main diagonal (k=0)
v = np.array([1, 2, 3])
d0 = np.diag(v, k=0)
print('np.diag([1, 2, 3], k=0):\n', d0)

# diagonal above main (k=1)
d1 = np.diag(v, k=1)
print('\nnp.diag([1, 2, 3], k=1):\n', d1)

# diagonal below main (k=-1)
d_1 = np.diag(v, k=-1)
print('\nnp.diag([1, 2, 3], k=-1):\n', d_1)

# extract diagonal with offset
mat = np.arange(1, 26).reshape(5, 5)
print('\nmat (3x5):\n', mat)
print('np.diag(mat, k=0):', np.diag(mat, k=0))
print('np.diag(mat, k=1):', np.diag(mat, k=1))
print('np.diag(mat, k=-1):', np.diag(mat, k=-1))

--- Diagonal Matrices with Offset ---

np.diag([1, 2, 3], k=0):
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

np.diag([1, 2, 3], k=1):
 [[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]

np.diag([1, 2, 3], k=-1):
 [[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]

mat (3x5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
np.diag(mat, k=0): [ 1  7 13 19 25]
np.diag(mat, k=1): [ 2  8 14 20]
np.diag(mat, k=-1): [ 6 12 18 24]
