# Broadcasting

Definition: Broadcasting in NumPy is a mechanism that allows operations on arrays of different shapes. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works forward. Two dimensions are compatible when: (1) they are equal, or (2) one of them is 1. Arrays with fewer dimensions are padded with 1s on the left until shapes align. This allows efficient element-wise operations without explicit loops or memory overhead.

Broadcasting Rules:

1. If arrays have different numbers of dimensions, pad the smaller with 1s on the left
2. Arrays are compatible in a dimension if they are equal or one is 1
3. The dimension with size 1 is stretched (broadcasted) to match the other
4. If dimensions are incompatible and neither is 1, an error is raised

Key points:

- Broadcasting makes code concise and avoids copying data unnecessarily
- Operations align from the rightmost (trailing) dimension
- A scalar (0-D) can be broadcasted to any shape
- Common use: apply a 1-D operation along each row/column of a 2-D array

In [4]:
import numpy as np

# Broadcasting scalar to array
print('--- Broadcasting Scalar to Array ---\n')

a = np.array([1, 2, 3, 4, 5])
scalar = 10

print('a:', a)
print('scalar:', scalar)
print('a + scalar:', a + scalar)
print('a * scalar:', a * scalar)

# Broadcasting 1-D to 2-D
print('\n--- Broadcasting 1-D to 2-D ---\n')

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
row_vector = np.array([10, 20, 30])

print('matrix (3x3):\n', matrix)
print('\nrow_vector (shape 3):', row_vector)
print('\nmatrix + row_vector (broadcasts row_vector to each row):\n', matrix + row_vector)

# Broadcasting with dimension of size 1
print('\n--- Broadcasting with Size-1 Dimension ---\n')

col_vector = np.array([[10], [20], [30]])  # shape (3, 1)
print('col_vector (shape 3x1):\n', col_vector)
print('\nmatrix + col_vector (broadcasts col_vector to each column):\n', matrix + col_vector)

--- Broadcasting Scalar to Array ---

a: [1 2 3 4 5]
scalar: 10
a + scalar: [11 12 13 14 15]
a * scalar: [10 20 30 40 50]

--- Broadcasting 1-D to 2-D ---

matrix (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

row_vector (shape 3): [10 20 30]

matrix + row_vector (broadcasts row_vector to each row):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

--- Broadcasting with Size-1 Dimension ---

col_vector (shape 3x1):
 [[10]
 [20]
 [30]]

matrix + col_vector (broadcasts col_vector to each column):
 [[11 12 13]
 [24 25 26]
 [37 38 39]]


In [5]:
import numpy as np

# Advanced broadcasting examples
print('--- Advanced Broadcasting Examples ---\n')

# Example 1: Normalize each row (subtract mean)
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]], dtype=float)

row_means = np.mean(matrix, axis=1, keepdims=True)  # shape (3, 1)
print('matrix:\n', matrix)
print('\nrow_means:\n', row_means)
normalized = matrix - row_means
print('\nnormalized (each row centered at 0):\n', normalized)

# Example 2: Scale each column
col_scale = np.array([1, 10, 100])  # shape (3,)
print('\n--- Scaling Columns ---')
print('col_scale:', col_scale)
scaled = matrix * col_scale
print('matrix * col_scale:\n', scaled)

# Example 3: Reshape for broadcasting
print('\n--- Reshape for Broadcasting ---')
a = np.array([1, 2, 3])        # shape (3,)
b = np.array([[1], [2]])       # shape (2, 1)
result = a + b                  # broadcasts to (2, 3)
print('a (shape 3):', a)
print('b (shape 2x1):\n', b)
print('a + b (result shape 2x3):\n', result)

--- Advanced Broadcasting Examples ---

matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

row_means:
 [[2.]
 [5.]
 [8.]]

normalized (each row centered at 0):
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]

--- Scaling Columns ---
col_scale: [  1  10 100]
matrix * col_scale:
 [[  1.  20. 300.]
 [  4.  50. 600.]
 [  7.  80. 900.]]

--- Reshape for Broadcasting ---
a (shape 3): [1 2 3]
b (shape 2x1):
 [[1]
 [2]]
a + b (result shape 2x3):
 [[2 3 4]
 [3 4 5]]


In [6]:
import numpy as np

# Broadcasting shape incompatibility
print('--- Broadcasting Shape Compatibility ---\n')

# Compatible shapes
a = np.ones((3, 4))      # shape (3, 4)
b = np.ones((4,))        # shape (4,)
result = a + b
print('a shape:', a.shape)
print('b shape:', b.shape)
print('result shape:', result.shape)
print('Compatible: broadcast (4,) to (3, 4)\n')

# Another compatible case
c = np.ones((3, 1))      # shape (3, 1)
d = np.ones((3, 4))      # shape (3, 4)
result2 = c + d
print('c shape:', c.shape)
print('d shape:', d.shape)
print('result shape:', result2.shape)
print('Compatible: broadcast (3, 1) to (3, 4)\n')

# Uncomment to see incompatible case (will raise error):
# e = np.ones((2, 3))
# f = np.ones((4,))
# result3 = e + f  # ValueError: operands could not be broadcast together
# print('Incompatible shapes cannot broadcast!')

--- Broadcasting Shape Compatibility ---

a shape: (3, 4)
b shape: (4,)
result shape: (3, 4)
Compatible: broadcast (4,) to (3, 4)

c shape: (3, 1)
d shape: (3, 4)
result shape: (3, 4)
Compatible: broadcast (3, 1) to (3, 4)



# Random Functions

Definition: NumPy's random module provides functions to generate random numbers and arrays. Common functions include `np.random.rand()` (uniform [0,1)), `np.random.randn()` (standard normal), `np.random.randint()` (random integers), `np.random.choice()` (sample from array), and `np.random.shuffle()` (in-place shuffle). Use `np.random.seed()` to ensure reproducibility.

Key points:

- **`np.random.rand(d0, d1, ...)`**: uniform distribution on [0, 1)
- **`np.random.randn(d0, d1, ...)`**: standard normal distribution (mean=0, std=1)
- **`np.random.randint(low, high, size)`**: random integers from low (inclusive) to high (exclusive)
- **`np.random.choice(a, size, replace, p)`**: sample from array; `replace=True` allows repeats
- **`np.random.shuffle(a)`**: shuffle array in-place (modifies original)
- **`np.random.permutation(a)`**: return shuffled copy (does not modify original)
- **`np.random.seed(seed)`**: set seed for reproducibility; use same seed to get same sequence
- **`np.random.normal(loc, scale, size)`**: normal distribution with mean `loc` and std `scale`

In [7]:
import numpy as np

# Basic random functions
print('--- Basic Random Functions ---\n')

# rand: uniform [0, 1)
uniform = np.random.rand(5)
print('np.random.rand(5):', uniform)

# randn: standard normal distribution
normal = np.random.randn(5)
print('\nnp.random.randn(5):', normal)

# randint: random integers
integers = np.random.randint(1, 11, size=10)
print('\nnp.random.randint(1, 11, size=10):', integers)

# Multi-dimensional
matrix = np.random.rand(3, 4)
print('\nnp.random.rand(3, 4):\n', matrix)

--- Basic Random Functions ---

np.random.rand(5): [0.25903477 0.72404794 0.92442973 0.10666275 0.02014722]

np.random.randn(5): [-0.61882349 -1.18242841  1.61432285  0.42377224 -1.04631935]

np.random.randint(1, 11, size=10): [ 8  4  7  6  4 10  3  5  2  5]

np.random.rand(3, 4):
 [[0.30022774 0.81129778 0.43993466 0.63974969]
 [0.49321544 0.45698173 0.7596466  0.36295325]
 [0.4103503  0.17356354 0.72964063 0.30950018]]


In [8]:
import numpy as np

# choice, shuffle, and permutation
print('--- Choice, Shuffle, Permutation ---\n')

arr = np.array([10, 20, 30, 40, 50])
print('arr:', arr)

# choice: sample from array
sampled = np.random.choice(arr, size=5, replace=True)
print('\nnp.random.choice(arr, size=5, replace=True):', sampled)

# choice without replacement
sampled_nr = np.random.choice(arr, size=3, replace=False)
print('np.random.choice(arr, size=3, replace=False):', sampled_nr)

# shuffle: modify in-place
arr_copy = arr.copy()
np.random.shuffle(arr_copy)
print('\nAfter np.random.shuffle:')
print('original arr:', arr)
print('shuffled arr_copy:', arr_copy)

# permutation: return shuffled copy (non-destructive)
perm = np.random.permutation(arr)
print('\nnp.random.permutation(arr):', perm)
print('original arr (unchanged):', arr)

--- Choice, Shuffle, Permutation ---

arr: [10 20 30 40 50]

np.random.choice(arr, size=5, replace=True): [20 40 20 30 20]
np.random.choice(arr, size=3, replace=False): [30 40 50]

After np.random.shuffle:
original arr: [10 20 30 40 50]
shuffled arr_copy: [10 40 30 20 50]

np.random.permutation(arr): [10 40 20 50 30]
original arr (unchanged): [10 20 30 40 50]


In [13]:
import numpy as np

# Reproducibility with seed
print('--- Reproducibility with Seed ---\n')

# First run with seed 42
np.random.seed(42)
rand1 = np.random.rand(5)
print('First run (seed=42):', rand1)

# Second run with same seed produces identical sequence
np.random.seed(42)
rand2 = np.random.rand(5)
print('Second run (seed=42):', rand2)
print('Are they equal?', np.array_equal(rand1, rand2))

# Different seed gives different results
np.random.seed(123)
rand3 = np.random.rand(5)
print('\nWith seed=123:', rand3)

--- Reproducibility with Seed ---

First run (seed=42): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Second run (seed=42): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Are they equal? True

With seed=123: [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


In [14]:
import numpy as np

# Normal distribution and other distributions
print('--- Distributions ---\n')

# Normal distribution with custom mean and std
np.random.seed(42)
normal_custom = np.random.normal(loc=100, scale=15, size=10)
print('np.random.normal(loc=100, scale=15, size=10):', normal_custom)

# Exponential distribution
exponential = np.random.exponential(scale=2.0, size=10)
print('\nnp.random.exponential(scale=2.0, size=10):', exponential)

# Binomial distribution (n trials, p probability of success)
binomial = np.random.binomial(n=10, p=0.5, size=10)
print('\nnp.random.binomial(n=10, p=0.5, size=10):', binomial)

# Poisson distribution (lambda parameter)
poisson = np.random.poisson(lam=3.0, size=10)
print('\nnp.random.poisson(lam=3.0, size=10):', poisson)

--- Distributions ---

np.random.normal(loc=100, scale=15, size=10): [107.4507123   97.92603548 109.71532807 122.84544785  96.48769938
  96.48794565 123.68819223 111.51152094  92.95788421 108.13840065]

np.random.exponential(scale=2.0, size=10): [0.40135798 0.40522285 0.72550746 1.48785566 1.13107413 0.68844599
 1.89274175 0.30046906 0.69103102 0.91255444]

np.random.binomial(n=10, p=0.5, size=10): [5 6 4 5 5 2 5 3 3 8]

np.random.poisson(lam=3.0, size=10): [3 2 1 3 4 4 1 2 3 2]
